# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medicamento.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='medicamento.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11medicamento.proto\"\x07\n\x05\x45mpty\"h\n\x0bMedicamento\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63odigo\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\r\n\x05\x64roga\x18\x04 \x01(\t\x12\x1e\n\x04tipo\x18\x05 \x01(\x0b\x32\x10.TipoMedicamento\"-\n\x0fTipoMedicamento\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"\x1a\n\x07Inicial\x12\x0f\n\x07inicial\x18\x01 \x01(\t\"5\n\x0fMedicamentoList\x12\"\n\x0cmedicamentos\x18\x01 \x03(\x0b\x32\x0c.Medicamento2\xa5\x02\n\x0cMedicService\x12$\n\x06GetAll\x12\x06.Empty\x1a\x10.MedicamentoList\"\x00\x12\x32\n\nInsertType\x12\x10.TipoMedicamento\x1a\x10.TipoMedicamento\"\x00\x12\x32\n\nRemoveType\x12\x10.TipoMedicamento\x1a\x10.MedicamentoList\"\x00\x12&\n\x06Insert\x12\x0c.Medicamento\x1a\x0c.Medicamento\"\x00\x12\x31\n\tGetByType\x12\x10.TipoMedicamento\x1a\x10.MedicamentoList\"\x00\x12,\n\x0cGetByInicial\x12\x08.Inicial\x1a\x10.MedicamentoList\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)


_MEDICAMENTO = _descriptor.Descriptor(
  name='Medicamento',
  full_name='Medicamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Medicamento.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codigo', full_name='Medicamento.codigo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='Medicamento.nombre', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='droga', full_name='Medicamento.droga', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tipo', full_name='Medicamento.tipo', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=134,
)


_TIPOMEDICAMENTO = _descriptor.Descriptor(
  name='TipoMedicamento',
  full_name='TipoMedicamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TipoMedicamento.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='TipoMedicamento.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=181,
)


_INICIAL = _descriptor.Descriptor(
  name='Inicial',
  full_name='Inicial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inicial', full_name='Inicial.inicial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=209,
)


_MEDICAMENTOLIST = _descriptor.Descriptor(
  name='MedicamentoList',
  full_name='MedicamentoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='medicamentos', full_name='MedicamentoList.medicamentos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=264,
)

_MEDICAMENTO.fields_by_name['tipo'].message_type = _TIPOMEDICAMENTO
_MEDICAMENTOLIST.fields_by_name['medicamentos'].message_type = _MEDICAMENTO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Medicamento'] = _MEDICAMENTO
DESCRIPTOR.message_types_by_name['TipoMedicamento'] = _TIPOMEDICAMENTO
DESCRIPTOR.message_types_by_name['Inicial'] = _INICIAL
DESCRIPTOR.message_types_by_name['MedicamentoList'] = _MEDICAMENTOLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Medicamento = _reflection.GeneratedProtocolMessageType('Medicamento', (_message.Message,), {
  'DESCRIPTOR' : _MEDICAMENTO,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:Medicamento)
  })
_sym_db.RegisterMessage(Medicamento)

TipoMedicamento = _reflection.GeneratedProtocolMessageType('TipoMedicamento', (_message.Message,), {
  'DESCRIPTOR' : _TIPOMEDICAMENTO,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:TipoMedicamento)
  })
_sym_db.RegisterMessage(TipoMedicamento)

Inicial = _reflection.GeneratedProtocolMessageType('Inicial', (_message.Message,), {
  'DESCRIPTOR' : _INICIAL,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:Inicial)
  })
_sym_db.RegisterMessage(Inicial)

MedicamentoList = _reflection.GeneratedProtocolMessageType('MedicamentoList', (_message.Message,), {
  'DESCRIPTOR' : _MEDICAMENTOLIST,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:MedicamentoList)
  })
_sym_db.RegisterMessage(MedicamentoList)



_MEDICSERVICE = _descriptor.ServiceDescriptor(
  name='MedicService',
  full_name='MedicService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=267,
  serialized_end=560,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='MedicService.GetAll',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MEDICAMENTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertType',
    full_name='MedicService.InsertType',
    index=1,
    containing_service=None,
    input_type=_TIPOMEDICAMENTO,
    output_type=_TIPOMEDICAMENTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveType',
    full_name='MedicService.RemoveType',
    index=2,
    containing_service=None,
    input_type=_TIPOMEDICAMENTO,
    output_type=_MEDICAMENTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Insert',
    full_name='MedicService.Insert',
    index=3,
    containing_service=None,
    input_type=_MEDICAMENTO,
    output_type=_MEDICAMENTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetByType',
    full_name='MedicService.GetByType',
    index=4,
    containing_service=None,
    input_type=_TIPOMEDICAMENTO,
    output_type=_MEDICAMENTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetByInicial',
    full_name='MedicService.GetByInicial',
    index=5,
    containing_service=None,
    input_type=_INICIAL,
    output_type=_MEDICAMENTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDICSERVICE)

DESCRIPTOR.services_by_name['MedicService'] = _MEDICSERVICE

# @@protoc_insertion_point(module_scope)
